---
permalink: faq/faq-configuration-and-supported-devices.html 
sidebar: sidebar 
keywords:  
summary: Estas preguntas frecuentes responden a preguntas comunes sobre la configuración de OnCommand Insight y los dispositivos compatibles. 
---
= Configuración y dispositivos compatibles
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Estas preguntas frecuentes responden a preguntas comunes sobre la configuración de OnCommand Insight y los dispositivos compatibles.



== ¿OCI realiza cambios en mi entorno?

No OCI es una herramienta de solo lectura que recopila información sobre su entorno. OCI nunca realiza cambios en sus activos ni en sus configuraciones.



== ¿Qué acceso a nivel de permiso necesita OCI para mis dispositivos?

En la mayoría de los casos en los que el dispositivo lo admite, solo se requiere un acceso de sólo lectura. Hay algunas soluciones que no permiten el acceso de sólo lectura y, por lo tanto, requerirían los permisos elevados adecuados.



== ¿Con qué frecuencia recopila información OCI?

OCI normalmente recopila datos de rendimiento cada 5 minutos y se descubren construcciones lógicas y físicas cada ½ hora OCI establece los intervalos de sondeo predeterminados según las prácticas recomendadas y la escalabilidad sugeridas, pero permite al usuario controlar todos estos intervalos.



== ¿Qué impacto tiene OCI en mi entorno?

Las comunicaciones IP pasivas, fuera de banda y sin agentes de OCI ayudan a minimizar la configuración, el mantenimiento y el impacto en el ecosistema del centro de datos. El equipo de desarrollo del rendimiento de OCI toma grandes medidas para minimizar cualquier impacto en el rendimiento del centro de datos en las actividades de supervisión del rendimiento en sí. El impacto se considera insignificante en los entornos operativos normales y se puede relajar o ajustar en plataformas tecnológicas altamente utilizadas o con un bajo rendimiento. Consulte la Guía de instalación de OnCommand Insight para obtener más información.



== ¿Cómo puedo enumerar todos los hosts/máquinas virtuales en OCI?

El complemento de OCI de widgets y posibilidades de listado de consultas se puede utilizar para proporcionar listas de estilos de inventario para activos del centro de datos. Las listas de máquinas virtuales hasta los husillos y numerosas construcciones entre sí se pueden poner a disposición de las consultas, widgets, paneles de control e informes del almacén de datos, y se puede acceder a ellas a través de la API RESTful.



== ¿OCI ofrece el mismo tipo de soporte para los hosts relacionados que no sean del hipervisor (como los servidores físicos)?

Los hipervisores como VMware proporcionan información detallada sobre los hosts ESXI y sus máquinas virtuales (VM) asociadas. En el caso de los servidores físicos, OCI recopila métricas hasta el HBA del host. OCI emplea un método único en el que detecta servidores físicos con una tecnología pendiente de patente. Una vez detectados los switches o el almacenamiento, los nombres de host de los servidores físicos se encuentran en la información del alias de la estructura. OCI selecciona estos nombres de host, los coincide con DNS y traslada automáticamente los hosts a OCI. Esta técnica reduce considerablemente la necesidad de actualizaciones de entrada manual y mantenimiento de inventario de herramientas.



== ¿OCI proporciona la misma profundidad (paridad) métrica del dispositivo en entornos heterogéneos?

Existen distintos grados de estandarización, similitud y nomenclatura en las plataformas de terceros y las tecnologías de los proveedores. OCI intenta normalizar la información sobre la capacidad y el rendimiento en un marco consistente. Algunas métricas de capacidad y rendimiento se proporcionan de forma nativa desde los contadores del dispositivo, como IOPS, latencia y capacidad bruta. Cuando no se proporcionan los contadores, OCI puede intentar resumir los valores (por ejemplo, sumando las IOPS o las capacidades de los volúmenes subyacentes) y, en los casos en que no esté disponible ninguna de ellas, OCI intentará derivar los valores métricos a través de distintos algoritmos computacionales. OCI ofrece una funcionalidad de integración de SNMP genérica para incorporar métricas adicionales que OCI no recopila actualmente.



== ¿OCI admite switches Fibre Channel?

Sí, además de recopilar datos de sus activos de almacenamiento, OCI también adquiere datos de inventario y rendimiento de los switches Cisco, Brocade y QLogic en su entorno.



== ¿Hay disponibles vistas de topología de toda la infraestructura? ¿OCI muestra «visibilidad completa»?

Sí, OCI detecta y asigna de forma dinámica los elementos lógicos y físicos, proporcionando una vista de topología integral e interactiva de tecnologías, estructuras, virtualizadores y almacenamiento back-end. Los iconos de topología permiten una rápida navegación de lanzamiento de los recursos afectados y ayudan a identificar las cargas de trabajo e infracciones en los entornos de almacenamiento compartido.
