---
permalink: config-admin/amazon-aws-ec2-data-source.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight utiliza este origen de datos para descubrir inventario y rendimiento de Amazon AWS EC2. 
---
= Origen de datos de Amazon AWS EC2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight utiliza este origen de datos para descubrir inventario y rendimiento de Amazon AWS EC2.



== Requisitos previos:

Para recopilar datos de los dispositivos Amazon EC2, debe disponer de la siguiente información:

* Debe tener el ID de clave de acceso IAM
* Debe tener la clave de acceso secreta de la cuenta de cloud de Amazon EC2
* Debe tener el privilegio "list organization"
* Puerto 433 HTTPS
* Las instancias EC2 se pueden notificar como una máquina virtual o (menos naturalmente) como un host. Los volúmenes de EBS se pueden notificar como un disco virtual usado por el equipo virtual, así como un almacén de datos que proporciona la capacidad para el disco virtual.


Las claves de acceso consisten en un ID de clave de acceso (por ejemplo, AKIAIOSFONDNN7EXAMPLE) y una clave de acceso secreta (por ejemplo, wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY). Utilice las claves de acceso para firmar solicitudes de programación que realice a EC@ si utiliza los SDK, REST o operaciones de API de consulta de Amanzon EC2. Estas claves se proporcionan con su contrato de Amazon.



== Cómo configurar este origen de datos

Para configurar el origen de datos de Amazon AWS EC2, necesitará el identificador de clave de acceso IAM de AWS y la clave de acceso secreta para su cuenta de AWS.

Rellene los campos de origen de datos según las tablas siguientes:



== Configuración:

|===


| Campo | Descripción 


 a| 
Región de AWS
 a| 
Seleccione la región de AWS



 a| 
Rol IAM
 a| 
Para su uso solo cuando se adquiere en una unidad de almacenamiento AU en AWS. Consulte a continuación para obtener más información sobre las funciones del IAM.



 a| 
ID de clave de acceso IAM de AWS
 a| 
Introduzca el ID de clave de acceso IAM de AWS. Se requiere si no utiliza el rol IAM.



 a| 
Clave de acceso secreta de AWS IAM
 a| 
Introduzca la clave de acceso secreta del IAM de AWS. Se requiere si no utiliza el rol IAM.



 a| 
Entiendo que AWS me facturará las solicitudes de API
 a| 
Compruebe esto para saber que AWS le da la razón de las solicitudes de API que ha realizado el sondeo de Insight

|===


== Configuración avanzada:

|===


| Campo | Descripción 


 a| 
Incluir regiones adicionales
 a| 
Especifique las regiones adicionales que se incluirán en el sondeo.



 a| 
Función de cuenta cruzada
 a| 
Función para acceder a los recursos de diferentes cuentas de AWS.



 a| 
Intervalo de sondeo de inventario (mín.)
 a| 
Intervalo entre sondeos de inventario (predeterminado 60 minutos)



 a| 
Tiempo de espera de conexión HTTP y socket (seg)
 a| 
Tiempo de espera de conexión HTTP (300 segundos predeterminado)



 a| 
Incluir etiquetas de AWS
 a| 
Haga clic en esto para habilitar la compatibilidad con etiquetas de AWS en anotaciones de Insight



 a| 
Intervalo de sondeo de rendimiento (s)
 a| 
Intervalo entre sondeos de rendimiento (predeterminado 1800 segundos)

|===


== Asignación de etiquetas de AWS a anotaciones de Insight

El origen de datos de AWS EC2 incluye una opción que permite completar anotaciones de Insight con etiquetas configuradas en AWS. Las anotaciones deben denominarse exactamente como etiquetas de AWS. Insight rellenará siempre anotaciones con el mismo nombre de tipo de texto y hará un "mejor intento" para rellenar anotaciones de otros tipos (número, booleano, etc.). Si la anotación es de un tipo diferente y el origen de datos no la rellena, puede ser necesario eliminar la anotación y volver a crearla como un tipo de texto.

Tenga en cuenta que AWS distingue mayúsculas de minúsculas, mientras que Insight no distingue mayúsculas de minúsculas. De este modo, si se crea una anotación denominada «PROPIETARIO» en Insight y etiquetas denominadas «PROPIETARIO», «propietario» y «propietario» en AWS, todas las variaciones de AWS del «propietario» se asignarán a la anotación de «PROPIETARIO» de Insight.

Información relacionada:

https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html["Administración de claves de acceso para usuarios de IAM"]



== Incluir regiones adicionales

En la sección AWS Data Collector *Configuración avanzada*, puede configurar el campo *incluir regiones adicionales* para que incluya regiones adicionales separadas por coma o punto y coma. De forma predeterminada, este campo se establece en *_US-.*_*, que recoge todas las regiones de AWS de EE.UU.. Para recopilar en _All_ regiones, establezca este campo en *_.*_*.

Si el campo *incluir regiones adicionales* está vacío, el recopilador de datos recopilará en los activos especificados en el campo *Región de AWS* según se especifica en la sección *Configuración*.



== *Recolección de cuentas secundarias de AWS*

Insight admite la colección de cuentas secundarias para AWS en un único recopilador de datos de AWS. La configuración de esta colección se realiza en el entorno AWS:

* Debe configurar cada cuenta secundaria para que tenga una función de AWS que permita que el ID de cuenta principal tenga acceso a los detalles de EC2 desde la cuenta secundaria.
* Cada cuenta secundaria debe tener el nombre de función configurado como la misma cadena
* Introduzca esta cadena de nombre de rol en la sección Insight AWS Data Collector *Configuración avanzada*, en el campo *función de cuenta cruzada*.


Práctica recomendada: Es muy recomendable asignar la directiva AmazonEC2ReadOnlyAccess predefinida de AWS a la cuenta principal de ECS. Además, el usuario configurado en el origen de datos debe tener al menos la directiva predefinida __AWSOrganizationsReadOnlyAccess__Policy asignada para consultar a AWS.

Consulte lo siguiente para obtener información sobre la configuración de su entorno para permitir que Insight recopile desde cuentas secundarias de AWS:

https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html["Tutorial: Delegue el acceso en las cuentas de AWS mediante roles IAM"]

https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_common-scenarios_aws-accounts.html["Configuración de AWS: Proporcionando acceso a un usuario IAM en otra cuenta de AWS que posee"]

https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user.html["Creación de un rol para delegar permisos en un usuario de IAM"]



== Roles IAM

Al utilizar la seguridad _IAM Role_, debe asegurarse de que el rol que cree o especifique tenga los permisos necesarios para acceder a los recursos.

Por ejemplo, si crea un rol IAM denominado _InstanceEc2ReadOnly_, debe configurar la política para conceder permiso de acceso a la lista de EC2 de solo lectura a todos los recursos EC2 de este rol IAM. Además, debe otorgar acceso STS (Security Token Service) para que esta función pueda asumir funciones en cuentas cruzadas.

Después de crear un rol IAM, puede adjuntarlo cuando crea una instancia nueva de EC2 o cualquier instancia existente de EC2.

Después de asociar el rol IAM _Instance2ReadOnly_ a una instancia de EC2, podrá recuperar la credencial temporal mediante metadatos de instancia mediante el nombre del rol IAM y utilizarla para acceder a los recursos de AWS mediante cualquier aplicación que se ejecute en esta instancia de EC2.


NOTE: El rol IAM se puede utilizar sólo cuando la unidad de adquisición se está ejecutando en una instancia de AWS.
