---
permalink: config-admin/anomalies.html 
sidebar: sidebar 
keywords:  
summary: La sección anomalías, que se muestra solo en una página de activos de la aplicación cuando se instala el motor de detección de anomalías, permite identificar el rango de carga de trabajo operativo normal de una aplicación e identificar cuándo los cambios en el rendimiento están fuera de los niveles esperados. 
---
= Anomalías
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La sección anomalías, que se muestra solo en una página de activos de la aplicación cuando se instala el motor de detección de anomalías, permite identificar el rango de carga de trabajo operativo normal de una aplicación e identificar cuándo los cambios en el rendimiento están fuera de los niveles esperados.

El análisis de anomalías proporciona visibilidad proactiva de la infraestructura que da soporte a aplicaciones vitales para el negocio e informa de las anomalías de rendimiento antes de que se conviertan en interrupciones del servicio. El motor de detección de anomalías de la aplicación procesa indicadores de rendimiento que recopila Insight e identifica anomalías en la infraestructura de la aplicación. Las anomalías son elementos, eventos o observaciones que no se ajustan a un patrón esperado u otros elementos. Utilice la detección de anomalías para:

* Controlar las aplicaciones críticas seleccionadas.
* Identifique cambios significativos en el comportamiento de la infraestructura de aplicaciones.
* Realice un seguimiento de una aplicación a través de toda la pila y de varios contadores.
* Diagnostique la causa de los eventos recurrentes periódicamente en una carga de trabajo de aplicaciones.
* Proporciona un conjunto más completo de información comparada con datos de contadores de rendimiento utilizando valores de umbral estáticos.
* Supervisión de modo reactivo mejorada con vista de extremo a extremo de la topología y la capacidad de centrarse en los comportamientos más anómalos de un conjunto de datos.

