---
permalink: config-admin/cdot-landing-page-terminology-storage.html 
sidebar: sidebar 
keywords:  
summary: Términos que se aplican a objetos o referencias que puede encontrar en las páginas de destino de activos de almacenamiento de Clustered Data ONTAP de NetApp. 
---
= Almacenamiento Clustered Data ONTAP de NetApp
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Términos que se aplican a objetos o referencias que puede encontrar en las páginas de destino de activos de almacenamiento de Clustered Data ONTAP de NetApp.



== Terminología de almacenamiento de Clustered Data ONTAP

Los siguientes términos se aplican a objetos o referencias que puede encontrar en las páginas de destino de activos de almacenamiento de Clustered Data ONTAP de NetApp. Muchos de estos términos también se aplican a otros recopiladores de datos.

* Modelo -- una lista delimitada por comas de los nombres de modelo de nodo discretos únicos dentro de este clúster. Si todos los nodos de los clústeres tienen el mismo tipo de modelo, solo aparecerá un nombre de modelo.
* Proveedor -- mismo nombre de proveedor que se vería si estuviera configurando un nuevo origen de datos.
* Número de serie: El número de serie de la matriz. En sistemas de almacenamiento de arquitectura en clúster como Clustered Data ONTAP de NetApp, este número de serie puede ser menos útil que los números de serie de «nodos de almacenamiento» individuales.
* IP -- generalmente serán los IP(s) o los hostname(s) tal como están configurados en el origen de datos.
* Versión de microcódigo -- firmware.
* Capacidad bruta -- base 2 suma de todos los discos físicos del sistema, sin importar su función.
* Latencia: Representación de lo que experimentan las cargas de trabajo que se enfrentan al host, tanto en lecturas como escrituras. Lo ideal es que OCI externe este valor directamente, pero no suele ser el caso. En lugar de que la cabina ofrezca esta configuración, OCI suele realizar un cálculo ponderado por IOPS derivado de las estadísticas de los volúmenes internos individuales.
* Rendimiento: Agregado de volúmenes internos.
* Administración: Puede contener un hipervínculo para la interfaz de administración del dispositivo. Creado mediante programación por el origen de datos de Insight como parte de los informes de inventario.

