---
permalink: config-admin/changing-user-passwords.html 
sidebar: sidebar 
keywords:  
summary: Un usuario con privilegios de administrador puede cambiar la contraseña de cualquier cuenta de usuario de OnCommand Insight definida en el servidor local. 
---
= Cambio de contraseñas de usuario
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un usuario con privilegios de administrador puede cambiar la contraseña de cualquier cuenta de usuario de OnCommand Insight definida en el servidor local.



== Antes de empezar

Deben haberse completado los siguientes elementos:

* Notificaciones a cualquier persona que inicie sesión en la cuenta de usuario que esté modificando.
* Nueva contraseña que se utilizará después de este cambio.




== Acerca de esta tarea

Cuando se usa este método, no es posible cambiar la contraseña de un usuario que se valida mediante LDAP.



== Pasos

. Inicie sesión con privilegios de administrador.
. En la barra de herramientas Insight, haga clic en *Admin*.
. Haga clic en *Configuración*.
. Haga clic en la ficha *usuarios*.
. Busque la fila que muestra la cuenta de usuario que desea modificar.
. A la derecha de la información del usuario, haga clic en *Editar cuenta de usuario*.
. Introduzca la nueva *Contraseña* y, a continuación, vuelva a introducirla en el campo de verificación.
. Haga clic en *Guardar*.

