---
permalink: config-admin/changing-oncommand-insight-internal-user-passwords.html 
sidebar: sidebar 
keywords:  
summary: Las directivas de seguridad pueden requerir cambiar las contraseñas en el entorno OnCommand Insight. Algunas de las contraseñas de un servidor existen en un servidor diferente del entorno, lo que requiere que cambie la contraseña en ambos servidores. Por ejemplo, al cambiar la contraseña de usuario de “inventario” en Insight Server, debe coincidir con la contraseña de usuario de “inventario” en el conector del servidor de almacén de datos configurado para ese Insight Server. 
---
= Cambiar contraseñas de usuario interno de OnCommand Insight
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las directivas de seguridad pueden requerir cambiar las contraseñas en el entorno OnCommand Insight. Algunas de las contraseñas de un servidor existen en un servidor diferente del entorno, lo que requiere que cambie la contraseña en ambos servidores. Por ejemplo, al cambiar la contraseña de usuario de "'Inventory'" en Insight Server, debe coincidir con la contraseña de usuario "'Inventory'" en el conector del servidor del almacén de datos configurado para ese Insight Server.



== Antes de empezar

[NOTE]
====
Debe comprender las dependencias de las cuentas de usuario antes de cambiar las contraseñas. Si no se actualizan las contraseñas en todos los servidores necesarios, se generarán errores de comunicación entre los componentes de Insight.

====


== Acerca de esta tarea

En la siguiente tabla se enumeran las contraseñas de usuario interno de Insight Server y se enumeran los componentes de Insight que tienen contraseñas dependientes que deben coincidir con la nueva contraseña.

|===


| Contraseñas de Insight Server | Cambios necesarios 


 a| 
_interno
 a| 



 a| 
adquisición
 a| 
LAU, RAU



 a| 
dwh_internal
 a| 
Almacén de datos



 a| 
hosts
 a| 



 a| 
inventario
 a| 
Almacén de datos



 a| 
raíz
 a| 

|===
En la tabla siguiente se enumeran las contraseñas de usuario internas del almacén de datos y se enumeran los componentes de Insight que tienen contraseñas dependientes que coinciden con la nueva contraseña.

|===


| Contraseñas de almacén de datos | Cambios necesarios 


 a| 
cognos_admin
 a| 



 a| 
dwh
 a| 



 a| 
dwh_Internal (se cambia mediante la interfaz de usuario de configuración del conector del servidor)
 a| 
Servidor de Insight



 a| 
dwususer
 a| 



 a| 
hosts
 a| 



 a| 
Inventario (modificado con la interfaz de usuario de configuración de Server Connector)
 a| 
Servidor de Insight



 a| 
raíz
 a| 

|===
*Cambio de contraseñas en la interfaz de usuario de configuración de la conexión del servidor DWH*

En la siguiente tabla se muestra la contraseña de usuario de la LAU y se enumeran los componentes de Insight que tienen contraseñas dependientes que deben coincidir con la nueva contraseña.

|===


| Contraseñas DE LAU | Cambios necesarios 


 a| 
adquisición
 a| 
Insight Server, RAU

|===