---
permalink: config-admin/configuring-anomaly-detection-for-applications.html 
sidebar: sidebar 
keywords:  
summary: Debe activar la detección de anomalías para supervisar el comportamiento anormal de la infraestructura de una aplicación. La supervisión de detección de anomalías está activada o desactivada sólo para aplicaciones. 
---
= Configurar las aplicaciones para la detección de anomalías
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe activar la detección de anomalías para supervisar la infraestructura de una aplicación en busca de un comportamiento anormal. La supervisión de detección de anomalías está activada o desactivada sólo para aplicaciones.



== Antes de empezar

* Debe haber instalado y configurado el motor de detección de anomalías.
* Debe haber asignado una aplicación al recurso informático (máquina virtual o host) para los activos para los que desee recibir información de detección de anomalías. Insight detecta el resto de los recursos automáticamente.




== Pasos

. Inicie sesión en la interfaz de usuario web de OnCommand Insight.
. Haga clic en *Administrar* y seleccione *aplicaciones*.
. Ubique la aplicación asignada al recurso de computación.
. En la sección *anomalías*, asegúrese de que el cuadro de control *Monitor* de la parte superior derecha de la sección muestra *ON* en lugar de *OFF*; si no, haga clic en cualquier parte del cuadro de control *Monitor* para cambiar el control a *ON*.
+
Puede supervisar simultáneamente hasta 48 aplicaciones para detectar anomalías.

+
El estado de la sección muestra "'Aprendizaje'" durante al menos una hora; el motor de detección de anomalías carga previamente hasta 14 días de los datos de rendimiento existentes para que el motor pueda conocer el comportamiento de su entorno. Después de que Insight Server realice el primer sondeo de los activos de su entorno, el motor de detección de anomalías calcula y devuelve una puntuación de la aplicación en ese momento.



*Información relacionada*

link:assigning-applications-to-assets.md#["Asignar aplicaciones a activos"]
