---
permalink: config-admin/e-series-landing-page-terminology-storage-pool.html 
sidebar: sidebar 
keywords:  
summary: Términos que se aplican a objetos o referencias que puede encontrar en las páginas de destino de activos de pools de almacenamiento E-Series de NetApp. 
---
= Pool de almacenamiento de E-Series
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Términos que se aplican a objetos o referencias que puede encontrar en las páginas de destino de activos de pools de almacenamiento E-Series de NetApp.



== Terminología de pools de almacenamiento E-Series

Los siguientes términos se aplican a objetos o referencias que puede encontrar en las páginas de destino de activos de pools de almacenamiento E-Series de NetApp. Muchos de estos términos también se aplican a otros recopiladores de datos.

* Almacenamiento: En qué cabina de almacenamiento vive este pool. Obligatorio.
* Tipo -- valor descriptivo de una lista de posibilidades enumeradas. Lo más habitual será «'Thin Provisioning» o «'Grupo RAID'».
* Nodo: Si la arquitectura de esta cabina de almacenamiento pertenece a un nodo de almacenamiento específico, su nombre se verá aquí como un hipervínculo a su propia página de destino.
* Utiliza Flash Pool -- valor Sí/no.
* Redundancia -- nivel de RAID o esquema de protección. E-Series informa «'RAID 7'» para pools DDP.
* Capacidad: Los valores aquí son los lógicos utilizados, la capacidad utilizable y la capacidad total lógica, así como el porcentaje utilizado en estos. Ambos valores incluyen la capacidad de «"conservación» de E-Series, lo que resulta en números y el porcentaje es superior a lo que puede mostrar la interfaz de usuario de E-Series.
* Capacidad sobrecomprometida: Si se utilizan tecnologías de eficiencia, se ha asignado una suma total de capacidad de volumen mayor que la capacidad lógica del pool de almacenamiento, el valor porcentual será mayor que 0 %.
* Snapshot: Las capacidades de Snapshot utilizadas y totales, si su arquitectura de pool de almacenamiento dedica parte de su capacidad a los segmentos, en exclusiva para los snapshots.
* Utilización: Valor de porcentaje que muestra el mayor porcentaje de actividad de disco de cualquier capacidad que contribuye a este pool de almacenamiento. El aprovechamiento de disco no tiene necesariamente una fuerte correlación con el rendimiento de la cabina: El aprovechamiento puede ser elevado debido a la recompilación de discos, a actividades de deduplicación, etc. en ausencia de cargas de trabajo condicionadas por el host. Asimismo, las implementaciones de replicación de muchas cabinas pueden impulsar el uso del disco sin mostrar como carga de trabajo de volumen.
* IOPS: La suma de IOPS de todos los discos que contribuyen a la capacidad de este pool de almacenamiento.
* Rendimiento: La suma del rendimiento de todos los discos que contribuyen a la capacidad de este pool de almacenamiento.

