---
permalink: config-admin/infinidat-infinibox-http-data-source.html 
sidebar: sidebar 
keywords:  
summary: 'El origen de datos Infinidat InfiniBox \(HTTP\) se utiliza para recopilar información del almacenamiento Infinidat InfiniBox. Debe tener acceso al nodo de gestión de InfiniBox.' 
---
= Fuente de datos Infinidat InfiniBox
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La fuente de datos Infinidat InfiniBox (HTTP) se utiliza para recopilar información del almacenamiento Infinidat InfiniBox. Debe tener acceso al nodo de gestión de InfiniBox.



== Terminología

OnCommand Insight adquiere la siguiente información de inventario a partir del origen de datos de InfiniBox. Para cada tipo de activo que adquiere Insight, se muestra la terminología más común utilizada en este activo. Al ver o solucionar problemas de este origen de datos, tenga en cuenta la siguiente terminología:

|===


| Plazo del proveedor/modelo | Insight plazo 


 a| 
Unidad
 a| 
Disco



 a| 
InfiniBox
 a| 
Reducida



 a| 
Nodo
 a| 
Nodo de almacenamiento



 a| 
Piscina
 a| 
Pool de almacenamiento



 a| 
Volumen
 a| 
Volumen



 a| 
Puerto FC
 a| 
Puerto



 a| 
Sistema de archivos
 a| 
Volumen interno



 a| 
Sistema de archivos
 a| 
Fileshare



 a| 
Exportaciones de sistemas de archivos
 a| 
Share

|===
[NOTE]
====
Estos son sólo mapas terminológicos comunes y es posible que no representen todos los casos de este origen de datos.

====


== Configuración

|===


| Campo | Descripción 


 a| 
Host InfiniBox
 a| 
Dirección IP o nombre de dominio completo del nodo de gestión de InfiniBox



 a| 
Nombre de usuario
 a| 
Nombre de usuario para el nodo de gestión de InfiniBox



 a| 
Contraseña
 a| 
Contraseña para el nodo de gestión de InfiniBox

|===


== Configuración avanzada

|===


| Campo | Descripción 


 a| 
Puerto TCP
 a| 
Puerto TCP utilizado para conectarse a InfiniBox Server (predeterminado 443 )



 a| 
Intervalo de sondeo de inventario (mín.)
 a| 
Intervalo entre sondeos de inventario (predeterminado 60 minutos)



 a| 
Tiempo de espera de conexión
 a| 
Tiempo de espera de conexión (60 segundos predeterminado)

|===