---
permalink: config-admin/listing-installed-oncommand-insight-packages.html 
sidebar: sidebar 
keywords:  
summary: Es posible mostrar una lista de los componentes de OnCommand Insight instalados que incluyen, entre otros, el inventario, la capacidad, las dimensiones, Y las vistas del almacén de datos. Es posible que el servicio de soporte al cliente le solicite esta información o que desee ver qué versiones de software se han instalado y cuándo se han instalado. 
---
= Enumerar los componentes de OnCommand Insight instalados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible mostrar una lista de los componentes de OnCommand Insight instalados que incluyen, entre otros, el inventario, la capacidad, las dimensiones, Y las vistas del almacén de datos. Es posible que el servicio de soporte al cliente le solicite esta información o que desee ver qué versiones de software se han instalado y cuándo se han instalado.



== Pasos

. En la barra de herramientas Insight, haga clic en *Admin* y seleccione *solución de problemas*.
. En la parte inferior de la página del área otras tareas, haga clic en el vínculo *solución avanzada de problemas*.
. En la página solución de problemas avanzada, haga clic en la ficha *Informes*.
. Haga clic en *Paquetes de software instalados*.

