---
permalink: config-admin/managing-security-on-the-data-warehouse.html 
sidebar: sidebar 
keywords:  
summary: La herramienta securityadmin le permite administrar opciones de seguridad en el servidor de Data Warehouse. La administración de seguridad incluye actualizar las contraseñas internas de los usuarios internos en el servidor DWH, crear copias de seguridad de la configuración de seguridad o restaurar las configuraciones con la configuración predeterminada. 
---
= Gestión de la seguridad en el almacén de datos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `securityadmin` La herramienta le permite administrar las opciones de seguridad en el servidor del almacén de datos. La administración de seguridad incluye actualizar las contraseñas internas de los usuarios internos en el servidor DWH, crear copias de seguridad de la configuración de seguridad o restaurar las configuraciones con la configuración predeterminada.



== Acerca de esta tarea

Utilice la `securityadmin` herramienta para gestionar la seguridad:

* Windows - `C:\Program Files\SANscreen\securityadmin\bin\securityadmin.bat`
* Linux: `/bin/oci-securityadmin.sh`


Consulte link:../config-admin/securityadmin-tool.html["Securityadmin"]la documentación para obtener más información.
