---
permalink: config-admin/managing-security-on-the-insight-server.html 
sidebar: sidebar 
keywords:  
summary: La herramienta securityadmin le permite administrar opciones de seguridad en el servidor de Insight. La gestión de seguridad incluye cambiar contraseñas, generar claves nuevas, guardar y restaurar configuraciones de seguridad creadas o restaurar configuraciones con la configuración predeterminada. 
---
= Gestión de la seguridad en el servidor de Insight
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `securityadmin` La herramienta le permite gestionar las opciones de seguridad en el servidor de Insight. La gestión de seguridad incluye cambiar contraseñas, generar claves nuevas, guardar y restaurar configuraciones de seguridad creadas o restaurar configuraciones con la configuración predeterminada.



== Acerca de esta tarea

Utilice la `securityadmin` herramienta para gestionar la seguridad:

* Windows - `C:\Program Files\SANscreen\securityadmin\bin\securityadmin.bat`
* Linux: `/bin/oci-securityadmin.sh`




== Pasos

. Inicie sesión de forma remota en Insight Server.
. Inicie la herramienta de administración de seguridad en modo interactivo: `securityadmin -i`
+
El sistema solicita credenciales de inicio de sesión.

. Introduzca el nombre de usuario y la contraseña de una cuenta con las credenciales "'Admin'".
. Seleccione *servidor*.
+
Están disponibles las siguientes opciones de configuración del servidor:

+
** *Backup*
+
Crea un archivo zip de copia de seguridad del almacén que contiene todas las contraseñas y claves y coloca el archivo en una ubicación especificada por el usuario o en las siguientes ubicaciones predeterminadas:

+
*** Windows - `C:\Program Files\SANscreen\backup\vault`
*** Linux: `/var/log/netapp/oci/backup/vault`


** *Restaurar*
+
Restaura la copia de seguridad zip del almacén que se creó. Una vez restaurada, todas las contraseñas y claves se revierten a valores existentes en el momento de la creación del backup.

+
[NOTE]
====
Restore se puede utilizar para sincronizar contraseñas y claves en varios servidores, por ejemplo: - Cambiar la clave de cifrado del servidor en un servidor - Crear una copia de seguridad del almacén - Restaurar la copia de seguridad del almacén en el segundo servidor

+

====
** *Cambiar clave de cifrado*
+
Cambie la clave de cifrado del servidor que se utiliza para cifrar o descifrar contraseñas de usuario proxy, contraseñas de usuario SMTP, contraseñas de usuario LDAP, etc.

+
[NOTE]
====
Al cambiar las claves de cifrado, debe realizar una copia de seguridad de la nueva configuración de seguridad para poder restaurarla después de una actualización o instalación.

====
** *Actualizar contraseña*
+
Cambiar contraseña de las cuentas internas que usa Insight. Se muestran las siguientes opciones:

+
*** _interno
*** adquisición
*** cognos_admin
*** dwh_internal
*** hosts
*** inventario
*** raíz




+
[NOTE]
====
Algunas cuentas necesitan sincronizarse cuando se cambian las contraseñas. Por ejemplo, si cambia la contraseña del usuario de "adquisición" en el servidor, deberá cambiar la contraseña del usuario de "adquisición" en la LAU, la RAU y las DWH para que coincidan. Además, al cambiar contraseñas, debe realizar una copia de seguridad de la nueva configuración de seguridad para poder restaurarla después de una actualización o instalación.

====
+
** *Restablecer valores predeterminados*
+
Restablece las claves y las contraseñas a los valores predeterminados. Los valores predeterminados son los que se proporcionan durante la instalación.

** *Salida*
+
Salga de la `securityadmin` herramienta.



. Elija la opción que desea cambiar y siga las indicaciones.

