---
permalink: config-admin/managing-security-on-an-rau.html 
sidebar: sidebar 
keywords: rekey 
summary: La herramienta securityadmin le permite administrar opciones de seguridad en Raus. Es posible que necesite realizar una copia de seguridad o restaurar una configuración de almacén, cambiar las claves de cifrado o actualizar las contraseñas de las unidades de adquisición. 
---
= Gestión de la seguridad en una RAU
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `securityadmin` La herramienta le permite gestionar las opciones de seguridad en Raus. Es posible que necesite realizar una copia de seguridad o restaurar una configuración de almacén, cambiar las claves de cifrado o actualizar las contraseñas de las unidades de adquisición.



== Acerca de esta tarea

Utilice la `securityadmin` herramienta para gestionar la seguridad:

* Windows - `C:\Program Files\SANscreen\securityadmin\bin\securityadmin.bat`
* Linux: `/bin/oci-securityadmin.sh`


Un escenario para actualizar la configuración de seguridad de la LAU/RAU es actualizar la contraseña de usuario de 'adquisición' cuando la contraseña de ese usuario se haya cambiado en el servidor. La LAU y todos los raus utilizan la misma contraseña que la del usuario de 'adquisición' del servidor para comunicarse con el servidor.

El usuario de "adquisición" solo existe en el servidor de Insight. La RAU o LAU inicia sesión como ese usuario cuando se conectan al servidor.

Consulte link:../config-admin\/security-management.html["Herramienta securityadmin"]las instrucciones para obtener más información.
