---
permalink: config-admin/managing-security-on-the-local-acquisition-unit.html 
sidebar: sidebar 
keywords:  
summary: 'La herramienta securityadmin le permite administrar opciones de seguridad en el usuario de adquisición local \(LAU\). La gestión de seguridad incluye la gestión de claves y contraseñas, el guardado y la restauración de configuraciones de seguridad que se crean o restauran con la configuración predeterminada.' 
---
= Gestión de la seguridad en la unidad de adquisición local
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `securityadmin` La herramienta permite administrar las opciones de seguridad en el usuario de adquisición local (LAU). La gestión de seguridad incluye la gestión de claves y contraseñas, el guardado y la restauración de configuraciones de seguridad que se crean o restauran con la configuración predeterminada.



== Antes de empezar

Debe tener `admin` privilegios para realizar tareas de configuración de seguridad.



== Acerca de esta tarea

Utilice la `securityadmin` herramienta para gestionar la seguridad:

* Windows - `C:\Program Files\SANscreen\securityadmin\bin\securityadmin.bat`
* Linux: `/bin/oci-securityadmin.sh`


Consulte link:../config-admin\/security-management.html["Herramienta securityadmin"]las instrucciones para obtener más información.
