---
permalink: config-admin/managing-security-on-the-local-acquisition-unit.html 
sidebar: sidebar 
keywords:  
summary: 'La herramienta securityadmin le permite administrar opciones de seguridad en el usuario de adquisición local \(LAU\). La gestión de seguridad incluye la gestión de claves y contraseñas, el guardado y la restauración de configuraciones de seguridad que se crean o restauran con la configuración predeterminada.' 
---
= Gestión de la seguridad en la unidad de adquisición local
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `securityadmin` La herramienta permite administrar las opciones de seguridad en el usuario de adquisición local (LAU). La gestión de seguridad incluye la gestión de claves y contraseñas, el guardado y la restauración de configuraciones de seguridad que se crean o restauran con la configuración predeterminada.



== Antes de empezar

Debe tener `admin` privilegios para realizar tareas de configuración de seguridad.



== Acerca de esta tarea

Utilice la `securityadmin` herramienta para gestionar la seguridad:

* Windows - `C:\Program Files\SANscreen\securityadmin\bin\securityadmin.bat`
* Linux: `/bin/oci-securityadmin.sh`




== Pasos

. Inicie sesión de forma remota en Insight Server.
. Inicie la herramienta de administración de seguridad en modo interactivo:
+
** Windows - `C:\Program Files\SANscreen\securityadmin\bin\securityadmin.bat -i`
** Linux: `/bin/oci-securityadmin.sh -i`
+
El sistema solicita credenciales de inicio de sesión.



. Introduzca el nombre de usuario y la contraseña de una cuenta con las credenciales "'Admin'".
. Seleccione *Unidad de adquisición local* para volver a configurar la configuración de seguridad de la unidad de adquisición local.
+
Se muestran las siguientes opciones:

+
** *Backup*
+
Crea un archivo zip de copia de seguridad del almacén que contiene todas las contraseñas y claves y coloca el archivo en una ubicación especificada por el usuario o en las siguientes ubicaciones predeterminadas:

+
*** Windows - `C:\Program Files\SANscreen\backup\vault`
*** Linux: `/var/log/netapp/oci/backup/vault`


** *Restaurar*
+
Restaura la copia de seguridad zip del almacén que se creó. Una vez restaurada, todas las contraseñas y claves se revierten a valores existentes en el momento de la creación del backup.

+
[NOTE]
====
Restore se puede utilizar para sincronizar contraseñas y claves en varios servidores, por ejemplo: - Cambiar claves de cifrado en la LAU - Crear una copia de seguridad del almacén - Restaurar la copia de seguridad del almacén en cada uno de los raus

====
** *Cambiar claves de cifrado*
+
Cambie las claves de cifrado AU utilizadas para cifrar o descifrar las contraseñas del dispositivo.

+
[NOTE]
====
Al cambiar las claves de cifrado, debe realizar una copia de seguridad de la nueva configuración de seguridad para poder restaurarla después de una actualización o instalación.

====
** *Actualizar contraseña*
+
Cambiar la contraseña de la cuenta de usuario de "adquisición".

+
[NOTE]
====
Algunas cuentas necesitan sincronizarse cuando se cambian las contraseñas. Por ejemplo, si cambia la contraseña del usuario de "adquisición" en el servidor, deberá cambiar la contraseña del usuario de "adquisición" en la LAU, la RAU y las DWH para que coincidan. Además, al cambiar contraseñas, debe realizar una copia de seguridad de la nueva configuración de seguridad para poder restaurarla después de una actualización o instalación.

====
** *Restablecer valores predeterminados*
+
Restablece la contraseña de usuario de adquisición y las claves de cifrado de usuario de adquisición a los valores predeterminados, los valores predeterminados son los que se proporcionan durante la instalación.

** *Salida*
+
Salga de la `securityadmin` herramienta.



. Elija la opción que desea configurar y siga las instrucciones.

