---
permalink: config-admin/microsoft-azure-netapp-files-data-source.html 
sidebar: sidebar 
keywords:  
summary: 'Este origen de datos adquiere datos de inventario y rendimiento para Azure NetApp Files \(ANF\).' 
---
= Origen de datos Azure NetApp Files
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Este origen de datos adquiere datos de inventario y rendimiento para Azure NetApp Files (ANF).



== Requisitos

A continuación se muestran los requisitos para configurar este origen de datos:

* Requisito de puerto: 443 HTTPS
* IP de REST de Azure Management (management.azure.com)
* Azure Service Principal Application (Cliente) ID (cuenta de usuario)
* Clave de autenticación principal de servicio Azure (contraseña de usuario)
* Debe configurar una cuenta de Azure para la detección de Cloud Insights.
+
Una vez que la cuenta se haya configurado correctamente y registre la aplicación en Azure, tendrá las credenciales necesarias para descubrir la instancia de Azure con Cloud Insights. En el siguiente enlace se describe cómo configurar la cuenta para la detección:

+
https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal[]





== Configuración

|===


| Campo | Descripción 


 a| 
ID de aplicación principal de servicios Azure (cliente)
 a| 
ID de inicio de sesión en Azure



 a| 
ID de inquilino de Azure
 a| 
ID de inquilino de Azure



 a| 
Clave de autenticación principal del servicio Azure
 a| 
Clave de autenticación de inicio de sesión



 a| 
Entiendo que Microsoft me factura por las solicitudes de API
 a| 
Marque esto para verificar que Microsoft le da la cuenta de las solicitudes de API que ha realizado el sondeo de Insight.

|===


== Configuración avanzada

|===


| Campo | Descripción 


 a| 
Intervalo de sondeo de inventario (mín.)
 a| 
El valor predeterminado es 60 minutos

|===