---
permalink: config-admin/qlogic-fc-switch-snmp-data-source.html 
sidebar: sidebar 
keywords:  
summary: 'Para la configuración, el origen de datos de QLogic FC Switch \(SNMP\) requiere la dirección de red del dispositivo FC Switch, especificado como una dirección IP, y una cadena de comunidad de solo lectura de SNMP que se usa para acceder al dispositivo.' 
---
= Fuente de datos del switch FC QLogic
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para la configuración, el origen de datos de QLogic FC Switch (SNMP) requiere la dirección de red del dispositivo FC Switch, especificado como una dirección IP, y una cadena de comunidad SNMP _de solo lectura_ que se utiliza para acceder al dispositivo.



== Configuración

|===


| *Campo* | *Descripción* 


 a| 
Conmutador SANsurfer
 a| 
Dirección IP o nombre de dominio completo para el conmutador SANSurfer



 a| 
Versión de SNMP
 a| 
Versión de SNMP



 a| 
Comunidad SNMP
 a| 
Cadena de comunidad SNMP



 a| 
Nombre de usuario
 a| 
Nombre de usuario del conmutador SANSurfer



 a| 
Contraseña
 a| 
Contraseña para el conmutador SANSurfer

|===


== Configuración avanzada

|===


| *Campo* | *Descripción* 


 a| 
Intervalo de sondeo de inventario (mín.)
 a| 
Intervalo entre sondeos de inventario (predeterminado 15 minutos)



 a| 
Protocolo de autenticación SNMP
 a| 
Protocolo de autenticación SNMP (sólo SNMPv3)



 a| 
Reintentos SNMP
 a| 
Número de intentos de reintento SNMP



 a| 
Tiempo de espera de SNMP (ms)
 a| 
Tiempo de espera de SNMP (5000 ms predeterminado)



 a| 
Habilite el solapamiento
 a| 
Seleccione esta opción para activar el solapamiento



 a| 
Tiempo mínimo entre solapamientos (seg)
 a| 
Tiempo mínimo entre intentos de adquisición activados por solapamientos (predeterminado 10 segundos)



 a| 
Nombre de la estructura
 a| 
El origen de datos informará del nombre de la estructura. Deje en blanco para informar el nombre de la estructura como WWN.



 a| 
Intervalo de sondeo de rendimiento (s)
 a| 
Intervalo entre sondeos de rendimiento (predeterminado 300 segundos)

|===