---
permalink: config-admin/using-options-in-the-preferences-tab.html 
sidebar: sidebar 
keywords:  
summary: La ficha Preferencias de resolución de dispositivos permite crear un programa de resolución automática, especificar proveedores de almacenamiento y cintas para incluir o excluir de la identificación y establecer opciones de búsqueda DNS. 
---
= Opciones de configuración en la ficha Preferencias
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La ficha Preferencias de resolución de dispositivos permite crear un programa de resolución automática, especificar proveedores de almacenamiento y cintas para incluir o excluir de la identificación y establecer opciones de búsqueda DNS.



== Programación de resolución automática

Una programación de resolución automática puede especificar cuándo se ejecuta la resolución automática del dispositivo:

|===


| Opción | Descripción 


 a| 
Cada
 a| 
Utilice esta opción para ejecutar la resolución automática del dispositivo en intervalos de días, horas o minutos.



 a| 
Todos los días
 a| 
Utilice esta opción para ejecutar la resolución automática del dispositivo diariamente a una hora específica.



 a| 
Manualmente
 a| 
Utilice esta opción para ejecutar la resolución automática del dispositivo de forma manual.



 a| 
En cada cambio de entorno
 a| 
Utilice esta opción para ejecutar la resolución automática del dispositivo siempre que haya un cambio en el entorno.

|===
Si especifica manualmente, la resolución automática nocturna del dispositivo está desactivada.



== Opciones de procesamiento DNS

Las opciones de procesamiento DNS permiten seleccionar las siguientes funciones:

* Cuando el procesamiento de resultados de búsqueda DNS está habilitado, puede agregar una lista de nombres DNS para anexarlos a dispositivos resueltos.
* Puede seleccionar "'resolución automática de IP:'" para habilitar la resolución automática de host para los iniciadores y hosts iSCSI que acceden a recursos compartidos NFS mediante la búsqueda DNS. Si no se especifica esta opción, solo se lleva a cabo una resolución basada en FC.
* En los resultados, es posible optar por permitir guiones bajos en los nombres de host y utilizar un alias "conectado a" en lugar del alias de puerto estándar.




== Incluidos o excluyen proveedores específicos de cintas y almacenamiento

Puede incluir o excluir proveedores específicos de almacenamiento y cintas para su resolución automática. Tal vez desee excluir proveedores específicos si sabe, por ejemplo, que un host específico se convertirá en un host heredado y debería excluirse del nuevo entorno. También puede volver a agregar proveedores que ha excluido anteriormente pero que ya no desea excluir.

[NOTE]
====
Las reglas de resolución de dispositivos para cinta sólo funcionan para WWN donde el Proveedor para ese WWN está establecido en *incluido como sólo cinta* en las preferencias del proveedor.

====