---
permalink: faq/faq-additional-information.html 
sidebar: sidebar 
keywords: redhat,Linux 
summary: ¿Dónde puedo encontrar información adicional? 
---
= Información adicional
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
¿Dónde puedo obtener información adicional final sobre OnCommand Insight?



== Compatibilidad con fuentes de datos

Puede encontrar información sobre los orígenes de datos compatibles con Insight en la matriz de compatibilidad de orígenes de datos de OnCommand Insight. Se le pedirá que inicie sesión con sus credenciales del sitio de soporte de NetApp.

link:https://mysupport.netapp.com/api/content-service/staticcontents/content/products/oncommandinsight/DatasourceSupportMatrix_7.3.x.pdf["Matriz de compatibilidad de orígenes de datos de OnCommand Insight"]Matriz de compatibilidad para las versiones actuales compatibles de OnCommand Insight.



== Soporte técnico

link:https://mysupport.netapp.com/matrix["Herramienta de matriz de interoperabilidad de NetApp (IMT)"]Detalla los dispositivos y las plataformas que OnCommand Insight admite.

link:https://mysupport.netapp.com/site/products/all/details/oncommand-insight/guideme-tab["Solución de problemas guiada de NetApp"]La solución de problemas guiada proporciona, de manera bien documentada, contenido técnico, recursos de ayuda y procedimientos de solución problemas organizados por productos, funciones y tareas. Mediante el chat, es posible resolver problemas rápidamente sin necesidad de abrir un caso ni acudir al equipo de soporte técnico.

La base de conocimientos de NetApp permite acceder a artículos técnicos sobre la gestión y la administración de productos. Una pequeña parte de la base de conocimientos está disponible al público, Pero los usuarios registrados tendrán acceso a un abanico mucho más amplio de artículos técnicos de la base de conocimientos.

Contactos de los servicios globales de NetApp Póngase en contacto con el centro de soporte de su región.



== Comunidad NetApp

Storefront Download de NetApp desde una amplia colección de plantillas de informes, paquetes de soluciones, recopiladores de datos y ejemplos de scripting presentados por NetApp para OnCommand Insight.

Vídeos de OnCommand Insight Vea vídeos sobre una gran variedad de temas de nuestra lista de reproducción de vídeo de productos OnCommand Insight.

Los debates de la comunidad de Insight se unen al debate de OnCommand Insight.



== Otros

Documentación de IBM Cognos para IBM Cognos en la web.
