---
settings:
  name: OnCommand Insight
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr,it-it
sidebar:
  entries:
  - title: Documentos de OnCommand Insight
    url: "/index.html"
  - section: relnotes
  - section: overview
  - section: install-linux
  - section: install-windows
  - section: config-admin
  - section: dwh
  - section: reporting
  - section: faq
  - section: howto
  - title: Matriz de compatibilidad de recopilador de datos
    url: "/config-admin/reference_data_collector_support_matrix.html"
  - title: Avisos legales
    url: "/legal-notices.html"
