---
permalink: reporting/oncommand-insight-data-model-descriptions.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight incluye varios modelos de datos a partir de los cuales se pueden seleccionar informes predefinidos o crear un informe personalizado. 
---
= Modelos de datos de OnCommand Insight
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight incluye varios modelos de datos a partir de los cuales se pueden seleccionar informes predefinidos o crear un informe personalizado.

Cada modelo de datos contiene un simple data Mart y un Data Mart avanzado:

* El Data Mart simple proporciona un acceso rápido a los elementos de datos utilizados más comúnmente e incluye sólo la última instantánea de los datos de Data Warehouse; no incluye datos históricos.
* El Data Mart avanzado proporciona todos los valores y detalles disponibles desde el simple data Mart e incluye acceso a valores de datos históricos.
* *Modelo de datos de capacidad*
+
Le permite responder preguntas acerca de la capacidad de almacenamiento, el uso del sistema de archivos, la capacidad de volumen interno, la capacidad del puerto, la capacidad para qtrees, Y la capacidad de las máquinas virtuales (VM). El modelo de datos de capacidad es un contenedor para varios modelos de datos de capacidad. Puede crear informes que contesten varios tipos de preguntas mediante este modelo de datos:

+
** *Modelo de datos de capacidad de almacenamiento y agrupación de almacenamiento*
+
Le permite responder preguntas sobre la planificación de recursos de la capacidad de almacenamiento, incluidos los pools de almacenamiento y almacenamiento, e incluye datos de pools de almacenamiento físico y virtual. Este sencillo modelo de datos puede ayudarle a responder a preguntas relacionadas con la capacidad sobre el suelo y el uso de la capacidad de los pools de almacenamiento por nivel y centro de datos con el tiempo.

+
Si es el nuevo modelo de informes de capacidad, debe empezar por este modelo de datos, ya que es un modelo de datos más sencillo y objetivo. Con este modelo de datos, puede responder preguntas similares a las siguientes:

+
*** ¿Cuál es la fecha prevista para alcanzar el umbral de capacidad del 80% del almacenamiento físico?
*** ¿Cuál es la capacidad de almacenamiento físico de una cabina para un nivel determinado?
*** ¿Qué capacidad de almacenamiento tienen el fabricante, la familia y el centro de datos?
*** ¿Cuál es la tendencia de utilización de almacenamiento en un arreglo para todos los niveles?
*** ¿Cuáles son mis 10 sistemas de almacenamiento principales con un mayor aprovechamiento?
*** ¿Cuál es la tendencia de uso del almacenamiento de los pools de almacenamiento?
*** ¿Qué capacidad ya está asignada?
*** ¿Qué capacidad está disponible para la asignación?


** *Modelo de datos de utilización del sistema de archivos*
+
Le permite responder preguntas sobre el uso del sistema de archivos. Este modelo de datos ofrece visibilidad sobre el uso de la capacidad por parte de los hosts a nivel de sistema de archivos. Los administradores pueden determinar la capacidad asignada y utilizada por sistema de ficheros, determinar el tipo de sistema de ficheros e identificar las estadísticas de tendencias por tipo de sistema de ficheros. Puede responder a las siguientes preguntas utilizando este modelo de datos:

+
*** ¿Cuál es el tamaño del sistema de archivos?
*** ¿Dónde se almacenan los datos y cómo se accede a ellos, por ejemplo, local o SAN?
*** ¿Cuáles son las tendencias históricas de la capacidad del sistema de archivos? Entonces, en base a esto, ¿qué podemos prever para las necesidades futuras?


** *Modelo de datos de capacidad de volumen interno*
+
Permite responder a preguntas sobre la capacidad interna de volumen utilizado, la capacidad asignada y el uso de la capacidad a lo largo del tiempo:

+
*** ¿Qué volúmenes internos tienen un aprovechamiento superior a un umbral predefinido?
*** ¿Qué volúmenes internos corren el peligro de quedarse sin capacidad según una tendencia?
*** ¿Cuál es la capacidad utilizada respecto a la capacidad asignada de nuestros volúmenes internos?


** *Modelo de datos de capacidad de puerto*
+
Le permite responder preguntas acerca de la conectividad de los puertos del switch, el estado de los puertos y la velocidad de los puertos a lo largo del tiempo. Puede responder a preguntas similares para ayudarle a planificar la compra de switches nuevos:

+
*** ¿Cómo puedo crear una previsión de consumo de puertos que predice la disponibilidad de los recursos (puerto) (en función de la velocidad del centro de datos, del proveedor de switches y del puerto)?
*** ¿Qué puertos pueden quedarse sin capacidad y proporcionar velocidad de datos, centro de datos, proveedor y número de puertos de host y almacenamiento?
*** ¿Cuáles son las tendencias de capacidad de los puertos del switch con el tiempo?
*** ¿Cuáles son las velocidades de puerto?
*** ¿Qué tipo de capacidad de puerto es necesaria y qué organización está a punto de quedarse sin un determinado tipo de puerto o proveedor?
*** ¿Cuál es el momento adecuado para adquirir esa capacidad y hacerla disponible?


** *Modelo de datos de capacidad Qtree*
+
Permite tendencia al uso de qtrees (con datos como usar o la capacidad asignada) a lo largo del tiempo. Puede ver la información por diferentes dimensiones; por ejemplo, por entidad de negocio, aplicación, nivel y nivel de servicio. Puede responder a las siguientes preguntas utilizando este modelo de datos:

+
*** ¿Cuál es la capacidad usada para qtrees frente a los límites establecidos por aplicación o entidad empresarial?
*** ¿Cuáles son las tendencias de nuestra capacidad libre y usada para que podamos planificar la capacidad?
*** ¿Qué entidades de negocio utilizan más capacidad?
*** ¿Qué aplicaciones consumen la mayor capacidad?


** *Modelo de datos de capacidad de VM*
+
Le permite informar sobre el entorno virtual y el uso de su capacidad. Este modelo de datos le permite informar sobre los cambios en el uso de la capacidad a lo largo del tiempo en equipos virtuales y almacenes de datos. El modelo de datos también proporciona datos de pago por uso de equipos virtuales y thin provisioning.

+
*** ¿Cómo puedo determinar el pago por uso de la capacidad en función de la capacidad aprovisionada para los equipos virtuales y los almacenes de datos?
*** ¿Qué capacidad no utilizan los equipos virtuales y qué parte de los que no se utilizan está libre, huérfana u otra?
*** ¿Qué necesitamos comprar en función de las tendencias de consumo?
*** ¿Cuáles son los ahorros obtenidos con la eficiencia del almacenamiento gracias a las tecnologías de thin provisioning y deduplicación del almacenamiento? Las capacidades del modelo de datos de capacidad de máquinas virtuales están tomadas de discos virtuales (VMDK). Esto significa que el tamaño aprovisionado de una máquina virtual utilizando el modelo de datos de capacidad de la máquina virtual es el tamaño de sus discos virtuales. Esto es diferente de la capacidad aprovisionada en la vista de equipos virtuales de OnCommand Insight, que muestra el tamaño aprovisionado para los propios equipos virtuales.


** *Modelo de datos de capacidad de volumen*
+
Le permite analizar todos los aspectos de los volúmenes de su entorno y organizar los datos por proveedor, modelo, nivel, nivel de servicio y centro de datos. Es posible ver la capacidad relacionada con volúmenes huérfanos, volúmenes sin usar y volúmenes de protección (que se usan para la replicación). También puede ver diferentes tecnologías de volúmenes (iSCSI o FC) y comparar volúmenes virtuales con volúmenes no virtuales para problemas de virtualización de cabinas. Con este modelo de datos, puede responder preguntas similares a las siguientes:

+
*** ¿Qué volúmenes tienen un aprovechamiento superior a un umbral predefinido?
*** ¿Cuál es la tendencia de la capacidad de volumen huérfana en mi centro de datos?
*** ¿Qué cantidad de capacidad de mi centro de datos está virtualizada o con thin provisioning?
*** ¿Qué cantidad de capacidad de mi centro de datos debe reservarse para la replicación?




* *Modelo de datos de pago*
+
Le permite responder preguntas sobre la capacidad utilizada y la capacidad asignada de los recursos de almacenamiento (volúmenes, volúmenes internos y qtrees). Este modelo de datos proporciona información de pago por uso y responsabilidad de la capacidad de almacenamiento por hosts, aplicaciones y entidades de negocio, e incluye datos actuales e históricos. Los datos de los informes se pueden clasificar por nivel de servicio y nivel de almacenamiento.

+
Puede utilizar este modelo de datos para generar informes de pago por uso al encontrar la cantidad de capacidad que usa una entidad de negocio. Este modelo de datos le permite crear informes unificados de varios protocolos (incluidos NAS, SAN, FC e iSCSI).

+
** Para el almacenamiento sin volúmenes internos, los informes de pago por uso muestran el pago por uso por volúmenes.
** Para almacenamiento con volúmenes internos:
+
*** Si se asignan entidades de negocio a volúmenes, los informes de pago por uso muestran el pago por uso por volúmenes.
*** Si las entidades de negocio no están asignadas a volúmenes pero están asignadas a qtrees, los informes de pago por uso muestran un pago por uso por qtrees.
*** Si las entidades de negocio no están asignadas a volúmenes y no están asignadas a qtrees, los informes de pago por uso muestran el volumen interno.
*** La decisión de si se muestra el pago por uso por volumen, qtree o volumen interno se realiza por cada volumen interno, por lo que es posible que diferentes volúmenes internos del mismo pool de almacenamiento muestren el pago por uso en distintos niveles. Los hechos de la capacidad se purgan después de un intervalo de tiempo predeterminado. Para obtener más información, consulte procesos de almacén de datos.




+
Los informes que utilizan el modelo de datos de pago por uso pueden mostrar valores diferentes a los informes que utilizan el modelo de datos de capacidad de almacenamiento.

+
** Para las cabinas de almacenamiento que no son sistemas de almacenamiento de NetApp, los datos de ambos modelos de datos son los mismos.
** Para los sistemas de almacenamiento de NetApp y Celerra, el modelo de datos de pago por uso utiliza una sola capa (de volúmenes, volúmenes internos o qtrees) para basar sus cargos, mientras que el modelo de datos de capacidad de almacenamiento utiliza varias capas (de volúmenes y volúmenes internos) para basar sus cargos.


* *Modelo de datos de inventario*
+
Le permite responder a preguntas acerca de los recursos de inventario, incluidos hosts, sistemas de almacenamiento, switches, discos, cintas, qtrees, cuotas, equipos virtuales y servidores, y dispositivos genéricos. El modelo de datos Inventory incluye varios submarts que permiten ver información acerca de las replicaciones, rutas FC, rutas iSCSI, rutas NFS e infracciones. El modelo de datos de inventario no incluye datos históricos. Entre las preguntas que puede responder con este data Mart se incluyen las siguientes:

+
** ¿Qué activos tengo y dónde están?
** ¿Quién utiliza los activos?
** ¿Qué tipos de dispositivos tengo y cuáles son los componentes de esos dispositivos?
** ¿Cuántos hosts por SO tengo y cuántos puertos existen en esos hosts?
** ¿Qué cabinas de almacenamiento existen por proveedor en cada centro de datos?
** ¿Cuántos switches por proveedor tengo en cada centro de datos?
** ¿Cuántos puertos no tienen licencia?
** ¿Qué cintas del proveedor utilizamos y cuántos puertos hay en cada cinta?
** ¿Se identifican todos los dispositivos genéricos antes de comenzar a trabajar en los informes?
** ¿Cuáles son las rutas entre los hosts y los volúmenes o las cintas de almacenamiento?
** ¿Cuáles son los caminos entre los dispositivos genéricos y los volúmenes o las cintas de almacenamiento?
** ¿Cuántas infracciones de cada tipo tengo por centro de datos?
** Para cada volumen replicado, ¿cuáles son los volúmenes de origen y de destino?
** ¿Tengo alguna incompatibilidades del firmware o coincidencia incorrecta de velocidad del puerto entre switches y HBA del host Fibre Channel?


* *Modelo de datos de rendimiento*
+
Le permite responder preguntas sobre el rendimiento de volúmenes, volúmenes de aplicaciones, volúmenes internos, switches, aplicaciones, Máquinas virtuales, VMDK, ESX frente a nodos de máquinas virtuales, hosts y aplicaciones. Con este modelo de datos, puede crear informes que respondan a varios tipos de preguntas de gestión del rendimiento:

+
** ¿Qué volúmenes o volúmenes internos no se han utilizado o no se ha accedido a ellos durante un periodo específico?
** ¿Podemos determinar cualquier configuración incorrecta posible para el almacenamiento de una aplicación (sin utilizar)?
** ¿Cuál fue el patrón de comportamiento de acceso general de una aplicación?
** ¿Se asignan los volúmenes por niveles de forma adecuada para una aplicación determinada?
** ¿Podríamos utilizar almacenamiento más económico para una aplicación que se ejecute actualmente sin que ello afecte al rendimiento de la aplicación?
** ¿Cuáles son las aplicaciones que producen más acceso al almacenamiento configurado actualmente? Cuando utilice las tablas de rendimiento del conmutador, puede obtener la siguiente información:
** ¿Se equilibra mi tráfico de host a través de puertos conectados?
** ¿Qué interruptores o puertos están mostrando un gran número de errores?
** ¿Cuáles son los switches más utilizados en función del rendimiento de los puertos?
** ¿Cuáles son los switches infrautilizados en función del rendimiento de los puertos?
** ¿Cuál es el rendimiento de la tendencia del host en función del rendimiento de los puertos?
** ¿Cuál es la utilización del rendimiento de los últimos X días de un host, sistema de almacenamiento, cinta o switch específico?
** ¿Qué dispositivos producen tráfico en un conmutador específico (por ejemplo, qué dispositivos son responsables del uso de un conmutador altamente utilizado)?
** ¿Cuál es el rendimiento de una unidad de negocio específica en nuestro entorno? Cuando se utilizan las tablas de rendimiento de disco, se puede obtener la siguiente información:
** ¿Cuál es el rendimiento de un pool de almacenamiento específico en función de los datos de rendimiento de disco?
** ¿Cuál es el pool de almacenamiento más alto utilizado?
** ¿Cuál es el uso medio del disco para un almacenamiento específico?
** ¿Cuál es la tendencia de uso de un sistema de almacenamiento o un pool de almacenamiento en función de los datos de rendimiento de disco?
** ¿Cuál es la tendencia de uso de disco para un pool de almacenamiento específico? Si utiliza las tablas de rendimiento de máquinas virtuales y VMDK, puede obtener la siguiente información:
** ¿Tiene el mejor rendimiento posible mi entorno virtual?
** ¿Qué VMDK notifican las cargas de trabajo más altas?
** ¿Cómo se puede utilizar el rendimiento informado en los equipos virtuales asignados a distintos almacenes de datos para tomar decisiones sobre la reorganización en niveles. El modelo de datos de rendimiento incluye información que le ayuda a determinar la idoneidad de niveles, configuraciones erróneas de almacenamiento para aplicaciones y tiempos de último acceso de volúmenes y volúmenes internos. Este modelo de datos proporciona datos como tiempos de respuesta, IOPS, rendimiento, número de escrituras pendientes y estado de acceso.


* *Modelo de datos de eficiencia del almacenamiento*
+
Le permite realizar un seguimiento de la puntuación en eficiencia del almacenamiento y de su potencial a lo largo del tiempo. Este modelo de datos almacena mediciones no solo de la capacidad aprovisionada, sino también de la cantidad usada o consumida (la medición física). Por ejemplo, cuando se habilita thin provisioning, OnCommand Insight indica cuánta capacidad se toma del dispositivo. También puede usar este modelo para determinar la eficiencia cuando está activada la deduplicación. Puede responder a varias preguntas con el Data Mart de eficiencia del almacenamiento:

+
** ¿Cuáles son los ahorros que hemos conseguido en eficiencia del almacenamiento gracias a la implantación de tecnologías de thin provisioning y deduplicación?
** ¿Cuál es el ahorro de almacenamiento en los centros de datos?
** Según las tendencias de capacidad históricas, ¿cuándo necesitamos comprar almacenamiento adicional?
** ¿Qué aumento tendría la capacidad si habilitamos tecnologías como thin provisioning y deduplicación?
** En cuanto a la capacidad de almacenamiento, ¿estoy en riesgo ahora?



