---
permalink: install-windows/insight-java-ui-requirements.html 
sidebar: sidebar 
keywords:  
summary: Debido a que el cliente de interfaz de usuario de OnCommand InsightJava opera en un entorno Java de tiempo de ejecución en el equipo, es importante que se asegure de que su entorno cumple con requisitos específicos de sistema operativo, CPU y memoria. 
---
= Requisitos de la interfaz de usuario de Insight Java
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debido a que el cliente de interfaz de usuario de OnCommand InsightJava opera en un entorno Java de tiempo de ejecución en el equipo, es importante que se asegure de que su entorno cumple con requisitos específicos de sistema operativo, CPU y memoria.

Para acceder al cliente de interfaz de usuario de Java, debe instalar el entorno Java de tiempo de ejecución (JRE) en el equipo.

Para OnCommand Insight 7.3.2 y versiones posteriores, se necesita la versión de 64 bits de Java Runtime Environment (JRE) para ejecutar el cliente Java de Insight.

|===


| Componente | Requisito 


 a| 
De NetApp
 a| 
Cualquier máquina compatible con Java 8. El cliente basado en Java es compatible con las plataformas Windows, Macintosh y Linux.



 a| 
CPU
 a| 
Se requiere 1.8 GHz o superior.



 a| 
Memoria
 a| 
Se recomienda 2 GB o más. Si supervisa el rendimiento de centros de datos complejos (más de 50,000 puertos de switch), el servidor necesita más memoria. Esto sólo es aplicable si está instalada la licencia Perform.

|===