---
permalink: install-windows/installing-the-oncommand-insight-data-warehouse-and-reporting.html 
sidebar: sidebar 
keywords:  
summary: 'La instalación es independiente e incluye los elementos necesarios para ejecutar y utilizar el almacén de datos de OnCommand Insight \(DWH\) y las utilidades de informes.' 
---
= Instalación del almacén de datos y la elaboración de informes de OnCommand Insight
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La instalación es independiente e incluye los elementos necesarios para ejecutar y operar el almacén de datos OnCommand Insight (DWH) y las utilidades de informes.



== Antes de empezar

Tenga en cuenta lo siguiente antes de instalar o actualizar.

* Si está actualizando, haga una copia de seguridad de DWH.
* Debe tener __Administrator__permisos locales para instalar el almacén de datos de OnCommand Insight con Informes.
* Asegúrese de que el servicio Windows Modules Installer está activado (de forma automática o manual).
* Si se instala en una unidad que no sea C:, se deben habilitar los nombres de archivo cortos. Si no está activado, el instalador lo activará.
* Para el componente DB2, el usuario DB2 puede ser _domain_ user o _local_ user.
+
** Si el usuario de DB2 es un usuario _domain_, debe tener lo siguiente:
+
*** El usuario DB2 ya debe haberse creado y debe conocer el nombre de usuario y la contraseña
*** Como usuario que está instalando DWH con Informes, debe poder consultar al usuario de DB2. Puede validarlo con el comando:
+
**** `net user <db2 user name> /domain`




** Si el usuario de DB2 es un usuario _local_, debe tener lo siguiente:
+
*** Nombre de usuario y contraseña para el usuario que se utilizará para ejecutarse como Usuario DB2. Si este usuario no existe, la instalación la creará.


** [NOTA]




[]
====
El nombre de usuario DB2 así como el nombre de inicio de sesión de Windows tienen las siguientes restricciones: * Los caracteres válidos son: 'A' a 'Z'; 'a' a 'z'; '0' a '9'; '#'; '@'; '_'; '!'; '('; ')'; '{'; '}'; '-'; y '.'. * Si utiliza los caracteres especiales '!'; '('; ')'; '{'; '}'; '-'; y '.' se deben usar todas las letras mayúsculas para el nombre de usuario. * El primer carácter de la cadena debe ser un carácter alfabético, @, #, o $; no puede ser un número o las secuencias de letras _SYS_, _DBM_, o _IBM_ * no puede exceder 128 bytes de longitud. * No puede ser USUARIOS, ADMINISTRADORES, INVITADOS, PÚBLICO, LOCAL o cualquier palabra reservada de SQL.

====
* El usuario DB2 no puede ser el mismo que el usuario que realiza la instalación.




== Pasos

. Inicie sesión en el servidor del almacén de datos utilizando una cuenta con privilegios de administrador.
. Descargue el almacén de datos con el archivo .zip de Reporting y extraiga los archivos en una carpeta de instalación.
. Vaya a la carpeta _<download location>\oci_dwh_installer\_ y ejecute el script _install_oci_dwh.bat_.
+
[NOTE]
====
Con OnCommand Insight 7.3.10 y posterior, debe ejecutar la secuencia de comandos para una instalación correcta de DWH/Reporting. No ejecute el ejecutable de instalación .MSI.

====
. Introduzca el dominio DB2 o pulse Intro para el dominio local.
. Introduzca el nombre de usuario de DB2. Consulte arriba para ver las restricciones de nombre de usuario.
. Introduzca la contraseña del usuario de DB2. Vuelva a introducir la contraseña cuando se le solicite.
. Introduzca la ruta de instalación para el componente DB2 o pulse Intro para obtener los valores predeterminados.
. Se le presenta la información introducida. Verifique con cuidado todos los ajustes. Pulse Intro para iniciar la instalación.
. Si se le solicita, permita que Windows continúe con la instalación de DB2.
. Después de la instalación de DB2, se ejecutará el asistente de instalación de DWH. Siga las instrucciones para instalar DWH con Reporting.
+
El almacén de datos con instalación de informes puede tardar hasta una hora en completarse.


