---
permalink: install-windows/upgrading-data-warehouse.html 
sidebar: sidebar 
keywords:  
summary: Después de completar todas las tareas de requisitos previos, puede iniciar sesión en el servidor de almacén de datos y ejecutar el paquete de instalación para completar la actualización. 
---
= Actualizando almacén de datos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de completar todas las tareas de requisitos previos, puede iniciar sesión en el servidor de almacén de datos y ejecutar el paquete de instalación para completar la actualización.



== Acerca de esta tarea

El almacén de datos (DWH) no admite la actualización en línea. Siga estos pasos para actualizar a la nueva versión del software DWH.

[NOTE]
====
Al actualizar DWH, se elimina la carpeta que contiene la copia de seguridad del almacén de la herramienta _securityadmin_. Se recomienda realizar una copia de seguridad del almacén antes de actualizar DWH. Como referencia, las carpetas predeterminadas del almacén son las siguientes:

* Carpeta del almacén (almacenes en uso):``%SANSCREEN_HOME%\wildfly\standalone\configuration\vault``
* Backups de almacén: `%SANSCREEN_HOME%\backup\vault`


Consulte http://ie-docs.rtp.openeng.netapp.com/oci-73_ram/topic/com.netapp.doc.oci-acg/GUID-E3351676-2088-4767-AAB5-CB1D8476291C.html?resultof=%22%76%61%75%6c%74%22%20["Gestión de la seguridad en el almacén de datos"] si quiere más información.

====


== Pasos

. Inicie sesión en el servidor DWH utilizando una cuenta que tenga permisos de administrador local de Windows.
. Realice una copia de seguridad de la base de datos y los informes de DWH mediante la interfaz del portal de DWH.
. Haga una copia de seguridad de la configuración de seguridad si el servidor utiliza una configuración de seguridad no predeterminada.
. Desinstale el software DWH del servidor.
. Reinicie el servidor para eliminar componentes de la memoria.
. Instale la nueva versión de DWH en el servidor.
+
La instalación dura aproximadamente 2 horas. Se recomienda dejar todos los valores predeterminados seleccionados.

. Restaure la configuración de seguridad no predeterminada en el servidor DWH.
. Restaurar la base de datos DWH en el servidor.




== Después de terminar

Después de actualizar, debe restaurar la base de datos de Data Warehouse, que puede tardar tanto tiempo como más que la actualización.

[NOTE]
====
Durante una actualización de OnCommand Insight, no es extraño que un cliente cambie a un Insight Server diferente. Si ha cambiado el servidor Insight, después de restaurar la base de datos del almacén de datos, los conectores existentes señalarán a la dirección IP o el nombre de host del servidor anterior. Se recomienda eliminar el conector y crear uno nuevo para evitar posibles errores.

====