---
permalink: install-windows/upgrading-data-warehouse.html 
sidebar: sidebar 
keywords:  
summary: Después de completar todas las tareas de requisitos previos, puede iniciar sesión en el servidor de almacén de datos y ejecutar el paquete de instalación para completar la actualización. 
---
= Actualizando almacén de datos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de completar todas las tareas de requisitos previos, puede iniciar sesión en el servidor de almacén de datos y ejecutar el paquete de instalación para completar la actualización.



== Acerca de esta tarea

El almacén de datos (DWH) no admite la actualización en línea. Siga estos pasos para actualizar a la nueva versión del software DWH.

[NOTE]
====
*Debe hacer una copia de seguridad del almacén* antes de actualizar DWH.

Consulte link:../config-admin\/security-management.html["Herramienta securityadmin"]las instrucciones para obtener más información.

====


== Pasos

Al actualizar el almacén de datos, debe realizar las siguientes acciones:

. Después de instalar DWH 7,3.16, restaure el almacén y la base de datos en este orden:
+
.. Almacén
.. Base de datos


. Inicie sesión en el servidor DWH utilizando una cuenta que tenga permisos de administrador local de Windows.
. Realice una copia de seguridad de la base de datos y los informes de DWH mediante la interfaz del portal de DWH.
. Haga una copia de seguridad del almacén. Consulte link:../config-admin/security-management.html["Securityadmin"]la documentación.
. Desinstale el software DWH del servidor.
. Reinicie el servidor para eliminar componentes de la memoria.
. Instale la nueva versión de DWH en el servidor.
+
La instalación dura aproximadamente 2 horas. Se recomienda dejar todos los valores predeterminados seleccionados.

. Restaure el almacén en el servidor DWH.
. Restaurar la base de datos DWH en el servidor.




== Después de terminar

Después de actualizar, debe restaurar la base de datos de Data Warehouse, que puede tardar tanto tiempo como más que la actualización.

[NOTE]
====
Durante una actualización de OnCommand Insight, no es extraño que un cliente cambie a un Insight Server diferente. Si ha cambiado el servidor Insight, después de restaurar la base de datos del almacén de datos, los conectores existentes señalarán a la dirección IP o el nombre de host del servidor anterior. Se recomienda eliminar el conector y crear uno nuevo para evitar posibles errores.

====