---
permalink: install-linux/installing-oncommand-insight-data-warehouse-linux.html 
sidebar: sidebar 
keywords:  
summary: 'La instalación es independiente e incluye los elementos necesarios para ejecutar y operar el almacén de datos de OnCommand Insight \(DWH\).' 
---
= Instalación del almacén de datos OnCommand Insight
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La instalación es independiente e incluye los elementos necesarios para ejecutar y operar el almacén de datos OnCommand Insight (DWH).



== Antes de empezar

Debe haber completado todos los requisitos previos de instalación.



== Acerca de esta tarea

Data Warehouse cuenta con capacidades de generación de informes Cognos. Sin embargo, si instala Insight en un servidor Linux, puede utilizar estas funciones sólo si instala el almacén de datos en un servidor Windows. Para obtener información sobre la instalación del almacén de datos en las capacidades de generación de informes de Windows y Cognos, consulte la _OnCommand Insight Installation Guide for Microsoft Windows_.



== Pasos

. Inicie sesión en el servidor Data Warehouse utilizando una cuenta con privilegios sudo.
. Desplácese al directorio del servidor donde se encuentran los archivos de instalación y escriba el siguiente comando:
+
`unzip oci-dwh-<version>-linux-x86_64.zip`

+
Asegúrese de comprobar el número de versión del archivo de instalación; el número de versión puede ser diferente del que se muestra en el comando.

. Puede ver la sintaxis, los argumentos de comandos y el uso de los parámetros para `oci-install.sh` antes de iniciar la instalación:
+
`sudo ./oci-dwh-<version>-linux-x86_64/oci-install.sh --help`

. Ejecute el script de instalación:
+
`sudo ./oci-dwh-<version>-linux-x86_64/oci-install.sh`

+
Al instalar Insight Server o Data Warehouse en CentOS 9 Stream, Red Hat Enterprise Linux 9,4 u Oracle Linux 9,4, primero debe cambiar al directorio que contiene el archivo Installer y, a continuación, ejecutar el comando install con la opción de línea de comandos «--install-mysql-dependencies»:

+
....
cd /tmp/oci-7.3.16.1.297-linux-x86_64
sudo ./oci-install.sh --install-mysql-dependencies
....
. Lea el Contrato de licencia, acéptelo y siga las indicaciones.




== Resultados

Después de contestar todas las indicaciones, la instalación comienza y tarda aproximadamente 10 minutos, dependiendo de las aplicaciones instaladas.



== Sincronizar servidor y DWH


IMPORTANT: Después de instalar el Almacén de Datos, *Debe* sincronizar el Almacén de Datos con el Servidor OnCommand Insight. Siga estos pasos:

. En el sistema Servidor OnCommand Insight, inicie la herramienta *SecurityAdmin* en modo interactivo
+
 securityadmin -i
. Cambie la contraseña de los usuarios _INVENTORY_ y _dwh_INTERNAL_ por contraseñas de su elección. *Toma nota de estas contraseñas* como las necesitarás a continuación.
. Reinicie el servicio DWH
. En *Cada Conector* inicie la herramienta *SecurityAdmin* en modo interactivo. Necesitará las contraseñas que anotó en el paso 2 anterior.
+
 securityadmin -i
. Cambie las contraseñas de los usuarios _INVENTORY_ y _dwh_INTERNAL_ por las contraseñas utilizadas en el paso 2.
. Reinicie los servicios en los conectores.
. Agregue los Conectores a DWH, utilizando las contraseñas para los usuarios _INVENTORY_ y _dwh_INTERNAL_ del paso 2

