---
permalink: install-linux/installing-the-oncommand-insight-server-linux.html 
sidebar: sidebar 
keywords:  
summary: El servidor OnCommand Insight se instala mediante la línea de comandos. 
---
= Instalación del servidor OnCommand Insight
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El servidor OnCommand Insight se instala mediante la línea de comandos.



== Antes de empezar

Debe haber completado todos los requisitos previos de instalación.



== Pasos

. Inicie sesión en Insight Server con una cuenta con privilegios sudo.
. Desplácese al directorio del servidor donde se encuentran los archivos de instalación y escriba el siguiente comando:
+
`unzip oci-<version>-linux-x86_64.zip`

+
Asegúrese de comprobar el número de versión del archivo de instalación; el número de versión puede ser diferente del que se muestra en el comando.

. Puede ver la sintaxis, los argumentos de comandos y el uso de los parámetros para `oci-install.sh` :
+
`sudo ./oci-<version>-linux-x86_64/oci-install.sh --help`

. Ejecute el script de instalación:
+
`sudo ./oci-<version>-linux-x86_64/oci-install.sh`

+
Al instalar Insight Server en CentOS 9 Stream, Red Hat Enterprise Linux 9,4 u Oracle Linux 9,4, primero debe cambiar al directorio que contiene el archivo Installer y, a continuación, ejecutar el comando install con la opción de línea de comandos «--install-mysql-dependencies»:

+
....
cd /tmp/oci-7.3.16.1.297-linux-x86_64
sudo ./oci-install.sh --install-mysql-dependencies
....
. Lea el Contrato de licencia, acéptelo y siga las indicaciones.
. Si utiliza el modelo de licencias de consumo de Insight, debe habilitar el envío de información de uso a NetApp. Introduzca `Y` en este símbolo del sistema.




== Resultados

Después de contestar todas las indicaciones, la instalación comienza y tarda aproximadamente 10 minutos, dependiendo de las aplicaciones instaladas.

. Si va a instalar una unidad de adquisición remota (RAU), debe ejecutar la herramienta SecurityAdmin para crear una contraseña para el usuario _acquisition_. Necesitará esta contraseña al instalar la RAU.
+
Nota: Si ha creado esta contraseña, _NOT_ necesita sincronizar el servidor y la RAU como se indica a continuación.





== Sincronizar servidor con DWH y RAU


IMPORTANT: Después de instalar la Unidad de Adquisición Remota y/o el Almacén de Datos, *DEBE* sincronizar la RAU/DWH con el Servidor OnCommand Insight. Siga los pasos que se indican a continuación:

link:../install-windows/installing-a-remote-acquisition-unit-rau.html#synchronize-server-and-rau["Sincronizar servidor y RAU (Windows)"]

link:../install-windows/installing-the-oncommand-insight-data-warehouse-and-reporting.html#synchronize-server-and-dwh["Sincronizar servidor y DWH (Windows)"]

link:../install-linux/installing-a-remote-acquisition-unit-rau-linux.html#synchronize-server-and-rau["Sincronizar servidor y RAU (Linux)"]

link:../install-linux/installing-oncommand-insight-data-warehouse-linux.html#synchronize-server-and-dwh["Sincronizar servidor y DWH (Linux)"]
