---
permalink: install-linux/installation-prerequisites.html 
sidebar: sidebar 
keywords:  
summary: Antes de instalar OnCommand Insight, debe descargar la versión de software actual, adquirir la licencia correspondiente y configurar el entorno. 
---
= Requisitos previos de la instalación
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de instalar OnCommand Insight, debe descargar la versión de software actual, adquirir la licencia correspondiente y configurar el entorno.

Antes de instalar OnCommand Insight, asegúrese de que dispone de lo siguiente:

* Los archivos de software OnCommand Insight en el paquete de instalación descargado para la versión actual
* Una licencia para utilizar la versión de OnCommand Insight descargada
* El entorno mínimo de hardware y software
+
El producto actual puede consumir recursos de hardware adicionales (debido a la funcionalidad mejorada del producto OnCommand Insight) que no se consumieron en versiones anteriores del producto de OnCommand Insight.

* Un plan de implementación que incluye las configuraciones de hardware y red para el servidor OnCommand Insight, almacén de datos e informes y unidades de adquisición remota.
* Java 8 para la interfaz de usuario Java de OnCommand Insight.
+

NOTE: OnCommand Insight incluye una licencia de Oracle de pago para Java se 8. Los clientes no tienen que comprar ninguna licencia adicional de Java se 8. Esta licencia cubre el uso de Java se 8 con todos los componentes OCI. Consulte la link:legal-notices.html["Avisos"] para obtener detalles específicos.


