---
permalink: install-linux/upgrading-ethernet-monitoring-units.html 
sidebar: sidebar 
keywords:  
summary: Después de actualizar el software Insight Server, debe actualizar el software de supervisión ethernet. 
---
= Actualización del software de la unidad de supervisión Ethernet
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de actualizar el software Insight Server, debe actualizar el software de supervisión ethernet.



== Acerca de esta tarea

[NOTE]
====
La unidad de supervisión Ethernet (EMU) no se admite en OnCommand Insight versión 7.3.12 y posteriores.

====


== Pasos

. Inicie sesión en el servidor de la Unidad de supervisión Ethernet (EMU) utilizando una cuenta con privilegios sudo.
. Descargue el software Insight EMU del sitio de soporte de NetApp.
. Desplácese hasta el directorio de descarga y escriba el comando siguiente:
+
`unzip oci-ethernet-<version>-linux-x86_64.zip`

+
Asegúrese de tener el número de versión correcto del archivo de instalación.

. Puede ver la sintaxis, los argumentos de comandos y el uso de los parámetros para `oci-install.sh` :
+
`sudo ./oci-ethernet-<version>-linux-x86_64/oci-install.sh --help`

. Ejecute el script de instalación:
+
`sudo ./oci-ethernet-<version>-linux-x86_64/oci-install.sh`

. Acepte el Contrato de licencia y siga las indicaciones.

