---
permalink: install-linux/upgrading-the-anomaly-detection-engine.html 
sidebar: sidebar 
keywords:  
summary: A partir de la versión 7.3.9 de OnCommand Insight, puede realizar una actualización en línea del software de detección de anomalías. La actualización en línea conserva los datos de detección de anomalías y las puntuaciones de anomalías. 
---
= Actualización del motor de detección de anomalías
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de la versión 7.3.9 de OnCommand Insight, puede realizar una actualización en línea del software de detección de anomalías. La actualización en línea conserva los datos de detección de anomalías y las puntuaciones de anomalías.



== Antes de empezar

* El sistema debe ejecutar OnCommand Insight 7.3.7 o una versión posterior.
* Se recomienda actualizar el servidor OnCommand Insight antes de actualizar el motor de detección de anomalías.




== Acerca de esta tarea

Siga estos pasos para actualizar:



== Pasos

. Desplácese hasta el directorio en el que se encuentra el instalador: `cd oci-prelert-<version>-linux-x86_64`
. Instale el software de actualización de detección de anomalías: `sudo ./oci-prelert-install.sh`
+
El software de detección de anomalías se registra correctamente en el servidor OnCommand Insight.


