---
permalink: dwh/viewing-storage-arrays-consolidation-issues.html 
sidebar: sidebar 
keywords:  
summary: Los datos de las cabinas de almacenamiento indicadas se derivan del mercado de datos de inventario. Para todas las cabinas de almacenamiento, hay una fila para cada conector que informa sobre ellas, así como el conector principal desde el que se toma cada cabina. 
---
= Visualizar problemas de consolidación de las cabinas de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los datos de las cabinas de almacenamiento indicadas se derivan del mercado de datos de inventario. Para todas las cabinas de almacenamiento, hay una fila para cada conector que informa sobre ellas, así como el conector principal desde el que se toma cada cabina.



== Pasos

. Inicie sesión en el portal del almacén de datos en `+https://hostname/dwh+`, donde `hostname` Es el nombre del sistema en el que está instalado el almacén de datos de OnCommand Insight.
. En el panel de navegación de la izquierda, haga clic en *solución de problemas*.
. En la sección *consolidación del chasis*, haga clic en *matrices DE almacenamiento SAN*.
. Opcionalmente, para filtrar los datos en esta vista, escriba una parte del texto en el cuadro Filtrar y haga clic en *filtro*. Para desactivar el filtro, elimine el texto del cuadro filtro y haga clic en *filtro*. Puede filtrar por nombre de almacenamiento, IP de almacenamiento, modelo de proveedor o ID de objeto de OnCommand Insight.
+
El filtro distingue entre mayúsculas y minúsculas.

. Revise los siguientes datos:
+
** *GUID*
+
Identificador único global para este tipo de dispositivo consolidado (cabina de almacenamiento)

** *Nombre*
+
El nombre de la cabina de almacenamiento consolidada tal y como aparece en el almacén de datos

** *IP*
+
La dirección IP de la cabina de almacenamiento consolidada

** *Proveedor y Modelo*
+
Nombre del proveedor que vende la cabina de almacenamiento consolidada y el número de modelo del fabricante

** *Conector principal*
+
Nombre del conector OnCommand Insight que era el origen real de los datos

** *Conectores disponibles*
+
Todos los conectores OnCommand Insight donde reside la cabina de almacenamiento consolidada

** *Insight ID*
+
ID de la cabina de almacenamiento consolidada en el chasis OnCommand Insight donde reside el conector principal

** *Tiempo de cambio de Insight*
+
Cuando se produjo una actualización en OnCommand Insight para la cabina de almacenamiento y cuando se actualizó la misma cabina de almacenamiento en otros servidores OnCommand Insight




