---
permalink: howto/creating-a-query-to-identify-netapp-root-aggregates.html 
sidebar: sidebar 
keywords:  
summary: Las consultas proporcionan una búsqueda a nivel granular basada en criterios seleccionados por el usuario. El uso de una consulta permite buscar volúmenes internos en el entorno que contienen el agregado raíz de NetApp. 
---
= Crear una consulta para identificar los agregados raíz de NetApp en su entorno
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las consultas proporcionan una búsqueda a nivel granular basada en criterios seleccionados por el usuario. El uso de una consulta permite buscar volúmenes internos en el entorno que contienen el agregado raíz de NetApp.



== Pasos

. En la interfaz de usuario web de OnCommand Insight, cree una consulta para identificar los agregados raíz de NetApp en su entorno: *Consultas* > *Nueva consulta* > *Seleccionar tipo de recurso*
. Haga clic en *Grupo de almacenamiento*
. Escriba el nombre del agregado raíz
+
En este ejemplo se utiliza «'aggr0'» para el nombre. Al crear un agregado, solo deben seguirse los siguientes requisitos para el nombre:

+
** Debe comenzar con una letra o un guión bajo (_).
** Puede contener solo letras, dígitos y guiones bajos.
** Puede tener 250 caracteres o menos. En la mayoría de los casos, el agregado es el nombre aggr0, aggr_0 o algo similar. Puede que requiera un proceso iterativo para identificar todos los agregados raíz de NetApp de su entorno.


. Haga clic en *Guardar* e introduzca un nombre para la nueva consulta.
+
Tal como se ha mencionado anteriormente, puede ser un proceso iterativo y requiere múltiples consultas para identificar todos los agregados raíz de NetApp.


