---
permalink: howto/preparation-and-prerequisites-for-servicenow-integration.html 
sidebar: sidebar 
keywords:  
summary: Antes de la integración, deben cumplirse los preparativos y requisitos previos necesarios para ServiceNow, Insight y el conector del middleware Python. 
---
= Preparación y requisitos previos para la integración de Service Now
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de la integración, deben cumplirse los preparativos y requisitos previos necesarios para ServiceNow, Insight y el conector del middleware Python.



== Flujo de trabajo recomendado

Se recomienda encarecidamente el siguiente flujo de trabajo al integrar ServiceNow con Insight:

. Despliegue primero el conector de middleware Python en su instancia de desarrollo.
. Una vez que haya confirmado que todos los fallos se han identificado y corregido en su instancia de desarrollo, implemente el conector en su instancia de prueba/etapa.
. Una vez que haya confirmado el funcionamiento correcto en su instancia de ensayo, implemente el conector en su instancia de producción.


Si se detectan problemas durante cualquiera de estas fases, siga los pasos de reversión y desactive el conector, solucione el problema y vuelva a desplegarlo.



== Requisitos previos generales:

* Puede utilizar un host independiente o VM (recomendado) o el host/VM del servidor Insight para alojar el conector de middleware python.
* Se recomienda encarecidamente realizar backups del servidor de producción Insight y ponerlo en marcha en una instancia de desarrollo.
* ServiceNow debe detectar con precisión servidores en CMDB.
* Insight debe detectar con precisión los entornos de almacenamiento y computación.
* Puerto 443 y 80 a la instancia de Insight Server y ServiceNow.




== Requisitos previos de ServiceNow:

* Se recomienda encarecidamente utilizar una instancia de desarrollo/prueba.
* Permiso para cargar los conjuntos de actualizaciones de ServiceNow.
* Permiso para crear usuarios.
* ServiceNow versión Jakarta o posterior




== Requisitos previos de Insight:

* Se recomienda encarecidamente utilizar una instancia de desarrollo/prueba.
* Permiso para crear usuarios (permisos de administrador).
* Se admite la versión 7.3.1 o posterior de Insight; sin embargo, para sacar el máximo partido a Insight, utilice la última versión.




== Requisitos previos del conector de middleware Python:

* Python versión 3.6 o superior instalado.
* Al instalar Python, active la casilla para activar todos los usuarios. Esto establece Python para ubicaciones de instalación de aplicaciones estándar.
* Al instalar Python, marque la casilla para permitir que el instalador actualice la ruta de acceso. De lo contrario, deberá actualizar la ruta manualmente.
* Descargue las bibliotecas Python *psnow* y *solicitudes*.

