---
sidebar: sidebar 
permalink: task_config_telegraf_dcos.html 
keywords: telegraf, installation, install, dcos 
summary: configuración de dcos 
---
= Recopilador de datos de DC/OS
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Insights utiliza este recopilador de datos para recopilar métricas de DC/OS.



== Instalación

. En *Observabilidad > Colectores*, haz clic en *+Recopilador de datos*. Elija *DC/OS*.
+
Si no ha configurado un agente para la colección, se le pedirá que lo haga link:task_config_telegraf_agent.html["instale un agente"] en su entorno.

+
Si ya ha configurado un agente, seleccione el sistema operativo o la plataforma adecuados y haga clic en *continuar*.

. Siga las instrucciones de la pantalla Configuración de DC/OS para configurar el recopilador de datos. Las instrucciones varían en función del tipo de sistema operativo o plataforma que utilice para recopilar datos.




== Configuración

La información de configuración se puede encontrar en https://docs.mesosphere.com["Documentación de DC/OS"].



== Objetos y contadores

Se recopilan los objetos siguientes y sus contadores:

[cols="<.<,<.<,<.<,<.<"]
|===
| Objeto | Identificadores | Atributos | Puntos de datos 


| dcos_node | dcos_container
dco_app | clúster
nombre del hostl
ruta (sólo campos del sistema de archivos)
interfaz (sólo campos de red)
id_contenedor
task_name | tiempo_actividad_sistema (float)
núcleos_cpu (flotantes)
cpu_total (flotante)
cpu_user (flotante)
sistema_cpu (flotante)
cpu_idle (flotante)
cpu_wait (flotante)
load_1min (flotante)
load_5min (flotante)
load_15min (flotante)
sistema de archivos_capacidad_total_bytes (int)
sistema de archivos_capacidad_utilizada_bytes (int)
sistema de archivos_capacidad_libre_bytes (int)
filesystem_inode_total (flotante)
filesystem_inode_used (flotante)
filesystem_inode_free (flotante)
memory_total_bytes (int)
memory_free_bytes (int)
memory_buffers_bytes (int)
memory_cached_bytes (int)
swap_total_bytes (int)
swap_free_bytes (int)
swap_used_bytes (int)
red_en_bytes (int)
bytes_de_salida_red (int)
network_in_paquetes (flotante)
paquetes_de_salida_red (flotantes)
network_in_shorted (float)
network_out_shorted (flotante)
network_in_errors (float)
network_out_errores (float)
process_count (flotante) 
|===


== Resolución de problemas

Puede encontrar información adicional en la link:concept_requesting_support.html["Soporte técnico"] página.
