---
sidebar: sidebar 
permalink: task_config_telegraf_consul.html 
keywords: telegraf, installation, install, consul 
summary: Configuración del recopilador de datos de Consul 
---
= Cónsul colector de datos
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Insights utiliza este recopilador de datos para recopilar mediciones del cónsul.



== Instalación

. En *Observabilidad > Colectores*, haz clic en *+Recopilador de datos*. Seleccione Cónsul.
+
Si no ha configurado un agente para la colección, se le pedirá que lo haga link:task_config_telegraf_agent.html["instale un agente"] en su entorno.

+
Si ya ha configurado un agente, seleccione el sistema operativo o la plataforma adecuados y haga clic en *continuar*.

. Siga las instrucciones de la pantalla Configuración del Cónsul para configurar el recopilador de datos. Las instrucciones varían en función del tipo de sistema operativo o plataforma que utilice para recopilar datos.




== Configuración

Puede encontrar información en la link:https://www.consul.io/docs/index.html["Documentación del Cónsul"].



== Objetos y contadores para consul

Se recopilan los objetos siguientes y sus contadores:

[cols="<.<,<.<,<.<,<.<"]
|===
| Objeto: | Identificadores: | Atributos: | Puntos de datos: 


| Cónsul | Espacio de nombres
ID de comprobación
Nodo de servicio | IP del nodo
SO del nodo
UUID de nodo
Nombre del nodo
Nombre del servicio
Nombre de comprobación
ID de servicio
Estado | Crítico
Pasajera
Advertencia 
|===


== Resolución de problemas

Puede encontrar información adicional en link:concept_requesting_support.html["Soporte técnico"] página.
