---
sidebar: sidebar 
permalink: task_config_telegraf_kubernetes.html 
keywords: telegraf, installation, install, kubernetes 
summary: Configuración del recopilador de datos de Kubernetes 
---
= Recopilador de datos de Kubernetes
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Insights utiliza este recopilador de datos para recopilar métricas de Kubernetes Pod, nodo y contenedor.



== Instalación

Para obtener instrucciones de instalación de Kubernetes, consulte link:task_config_telegraf_agent.html#kubernetes["Instalación del agente"] página.


NOTE: La información sobre * kube-state-Metricm* se ha trasladado al link:task_config_telegraf_agent.html#kubernetes["Instalación del agente"] página.



== Objetos y contadores

Se recopilan los objetos siguientes y sus contadores:

[cols="<.<,<.<,<.<,<.<"]
|===
| Objeto: | Identificadores: | Atributos: | Puntos de datos: 


| Contenedor de Kubernetes | Espacio de nombres
Pod
Contenedor
Clúster | Nodo de Kubernetes
Nombre del nodo
SO del nodo
UUID de nodo
IP del nodo | Nanosegundos de CPU
Uso de CPU Nanocores
Fallos de Página Principal de Memoria
Tamaño de Juego Residente de Memoria (RSS)
Conjunto de trabajo de memoria
Fallos de Página de Memoria
Uso de memoria
Sistema de archivos raíz disponible
Capacidad del sistema de archivos raíz
Sistema de archivos raíz utilizado 


| Nodo de Kubernetes | Nodo de Kubernetes
Clúster | Nombre del nodo
SO del nodo
UUID de nodo
IP del nodo | Uso de CPU Nanocores
Uso de CPU nanosegundos
Sistema de archivos disponible
Total del sistema de archivos
Sistema de archivos utilizado
Memoria disponible
Uso de memoria
Fallos de Página Principal de Memoria
Fallos de Página de Memoria
Tamaño de Juego Residente de Memoria (RSS)
Conjunto de trabajo de memoria
Errores de RX de Red (por Segundo)
Bytes de RX de Red (por segundo)
Errores de transmisión de red (por segundo)
Bytes de TX de red (por segundo)
Sistema de archivos de imágenes de tiempo de ejecución disponible
Sistema de Archivos de Imagen de Tiempo de Ejecución Utilizado
Capacidad del sistema de archivos de imágenes en tiempo de ejecución 


| Pod de Kubernetes | Espacio de nombres
Pod
Clúster | Nodo de Kubernetes
Nombre del nodo
IP del nodo
SO del nodo
UUID de nodo | Bytes de TX de red (por segundo)
Errores de transmisión de red (por segundo)
Bytes de RX de Red (por segundo)
Errores de RX de Red (por Segundo) 


| Volumen de Kubernetes Pod | Volumen
Pod
Clúster
Espacio de nombres | Nodo de Kubernetes
Nombre del nodo
UUID de nodo
IP del nodo
SO del nodo | Disponible
Capacidad
Utilizado 


| Contenedor del sistema Kubernetes | Contenedor del sistema
Nodo de Kubernetes
Clúster | Nombre del nodo
IP del nodo
SO del nodo
UUID de nodo | Uso de CPU Nanocores
Uso de CPU Nanosegundos de núcleo
Fallos de Página Principal de Memoria
Fallos de Página de Memoria
Tamaño de Juego Residente de Memoria (RSS)
Uso de memoria
Conjunto de trabajo de memoria
Sistema de archivos raíz disponible
Capacidad del sistema de archivos raíz
Sistema de archivos de logs disponible
Registra la capacidad del sistema de archivos 
|===


== Resolución de problemas

[cols="2*"]
|===
| Problema: | Pruebe lo siguiente: 


| Ejecuté el comando del instalador del agente de Kubernetes, pero no veo un pod de agente de Telegraf que se ejecute a través de:

 sudo kubectl --namespace ci-monitoring get pods | Compruebe si se han producido errores al desplegar DaemonSet:

 sudo kubectl --namespace ci-monitoring describe ds telegraf-ds

Si hay errores relacionados con SecurityContextConstraints, haga lo siguiente:

1. Generar el Telegraf DaemonSet YAML

 sudo kubectl --namespace ci-monitoring get ds telegraf-ds -o yaml > /tmp/telegraf-ds.yaml

2. Detener el servicio de Telegraf

 sudo kubectl --namespace ci-monitoring delete ds telegraf-ds

3. Crear la restricción de seguridad necesaria (consulte la sección “Configuración del agente para recopilar datos”)

4. Volver a crear el Telegraf DaemonSet 


| Configuré Telegraf para obtener información sobre mi clúster de Kubernetes, pero no veo ninguna información en Cloud Insights. Veo errores de "valor de campo de encabezado no válido" en el archivo de registro de Telegraf que pertenece al plugin de entrada de kubernetes configurado. | Asegúrese de que el archivo de referencia bearer_token no tenga una nueva línea final. Para verificarlo, ejecute el siguiente comando y confirme que devuelve 0:

 cola -c1 <bearer_token_file> 
|===
Puede encontrar información adicional en link:concept_requesting_support.html["Soporte técnico"] página.
